# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\favorite_cities_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(79, 221, 301, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.citiesVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.citiesVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.citiesVerticalLayout.setObjectName("citiesVerticalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 220, 71, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.buttonsVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.buttonsVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsVerticalLayout.setObjectName("buttonsVerticalLayout")
        self.favCitiesLabel = QtWidgets.QLabel(Form)
        self.favCitiesLabel.setGeometry(QtCore.QRect(50, 190, 171, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.favCitiesLabel.setFont(font)
        self.favCitiesLabel.setObjectName("favCitiesLabel")
        self.removeLabel = QtWidgets.QLabel(Form)
        self.removeLabel.setGeometry(QtCore.QRect(260, 190, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.removeLabel.setFont(font)
        self.removeLabel.setObjectName("removeLabel")
        self.backLinkButton = QtWidgets.QCommandLinkButton(Form)
        self.backLinkButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.backLinkButton.setObjectName("backLinkButton")
        self.setDefaultLabel = QtWidgets.QLabel(Form)
        self.setDefaultLabel.setGeometry(QtCore.QRect(280, 40, 158, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setDefaultLabel.setFont(font)
        self.setDefaultLabel.setStyleSheet("background-color: rgb(125, 179, 206);")
        self.setDefaultLabel.setObjectName("setDefaultLabel")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(280, 80, 158, 31))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.favCitiesLabel.setText(_translate("Form", "Favorite cities"))
        self.removeLabel.setText(_translate("Form", "Remove from favorites"))
        self.backLinkButton.setText(_translate("Form", "Back"))
        self.setDefaultLabel.setText(_translate("Form", "Select the default city"))
